name: BDD Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Wishlists
        uses: actions/wishlists@v2

      - name: Install libraries for PostgreSQL
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Run the server locally
        run: |
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=critical --bind=0.0.0.0:8080 service:app &
          sleep 5
          curl -I http://localhost:8080/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/testdb"

      - name: Run unit tests with behave
        run: behave